[Seat:*]
autologin-user=auraos
autologin-user-timeout=0
user-session=auraos
greeter-session=lightdm-greeter
session-wrapper=/etc/X11/Xsession

[SeatDefaults]
allow-guest=false
greeter-hide-users=false
session-cleaner=/usr/bin/auraos-cleaner
